### ISSUE TITLE
[Member Registration] Display different frames based on registration period

### ISSUE THREAD

**Issue by babycroc** [academic-relations/ar-002-clubs#1067]
# 제안 내용 \*

등아리 등록 기간일 때에는 "동아리 등록" section이, 
회원 등록 기간일 때에는 "회원 등록" section이 보이게 해주세요!
두 기간 모두 아닐 때에는 "동아리 신청 내역" 자체를 통째로 숨겨주세요

(참고) https://www.figma.com/design/gm0BeqvuY5dsA86XyRgEc3/%ED%95%99%EC%88%A0%ED%98%91%EB%A0%A5-02.-%5B%EB%8F%99%EC%97%B0%ED%98%91%EB%A0%A5%EC%82%AC%EC%97%85%5D?node-id=7941-45483&node-type=section&t=Rwf0Bi633cRbkkeP-11

## 스크린샷

<img width="1040" alt="image" src="https://github.com/user-attachments/assets/fc7663e5-3b49-4d73-acc7-ab20af4a901e">

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by malloc3141** [comment]
이미 코드 상에 구현되어 있는 부분이라서 이슈 닫겠습니당
