### ISSUE TITLE
Fix Member Registration Error in MembersManageTable

### ISSUE THREAD

**Issue by ChaeyeonAhn** [academic-relations/ar-002-clubs#1087]
# 이슈 내용 \*

대표자로 로그인하여 /manage-club 들어가면 동아리 등록 신청자 내역이 제대로 뜨지 않음
- 문제 1: 조드 타입 호환이 안 돼서
- 문제 2: 승인 된 신청자 row에 반려 버튼 제대로 안 나타남 => 완료
- 문제 3: 승인 잘 되는지 확인 (새로고침 해야 된다는 문제) 

## 스크린샷

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by babycroc** [comment]
짱이양
