### ISSUE TITLE
[Member Registration] Fix register button flicker on club detail page

### ISSUE THREAD

**Issue by babycroc** [academic-relations/ar-002-clubs#1120]
# 이슈 내용 \*

이미 승인이 된 동아리에 대해 새로고침하면 "승인" 버튼 깜빡임
(동아리 목록에서도 동일할지도? 확인 필요)

https://github.com/user-attachments/assets/0ab5e62b-5883-4157-97d1-b72f43df13d8

## 스크린샷

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by wjeongchoi** [comment]
동아리 목록에서도 동일한 문제 발생
