### ISSUE TITLE
Update Favicon

### ISSUE THREAD

**Issue by jinhyeonkwon** [academic-relations/ar-002-clubs#1140]
# 제안 내용 \*

기본 favicon을 clubs 로고로 변경합니다

## 스크린샷

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by jinhyeonkwon** [comment]
현재 갑자기 favicon이 안 뜨는 문제가 생겨버려서.. 다른 필수 task 해결하고 돌아오겠습니다

**Comment by jinhyeonkwon** [comment]
다른 branch에서도 안 보이는 걸로 보아 제 쪽 문제인 것 같습니다..

**Comment by babycroc** [comment]
옹 마자 사실 나도 돌려봤는데 안 떠서 으잉 하긴 함 ㅋㅋㅋㅋㅋㅋ
