### ISSUE TITLE
FoldableSectionTitle as common component

### ISSUE THREAD

**Issue by babycroc** [academic-relations/ar-002-clubs#148]
# 제안 내용 \*

`FoldableSectionTitle`이 여러 곳에서 이용되고 있음
- `packages/web/src/features/clubs/components/FoldableSectionTitle.tsx`
- `packages/web/src/features/manage-club/funding/component/_atomic/FoldableSectionTitle.tsx`
- 앞으로 더 생길 듯

common component로 빼서 사용하자

## 스크린샷

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by wjeongchoi** [comment]
features/clubs에서 사용되는 FoldableSectionTitle랑 manage-club/funding에서 만든 FoldableSectionTitle이 기능이 약간 다른데 features/clubs에서 쓰이는 것도 수정할까요?
manage-club/funding에서 만든 건 common으로 쓰면 될 것 같은데 features/clubs에서 같은 걸로 쓰려면 clubs 페이지를 좀 수정해야 할 것 같아요
