### ISSUE TITLE
Impl Header NavSubMenu

### ISSUE THREAD

**Issue by babycroc** [academic-relations/ar-002-clubs#16]
# 제안 내용 \*

`Header`의 `NavSubMenu` 컴포넌트를 구현한다

일단 url path는 각 페이지가 개발되기 전까지 "/"로 놔둬도 될 것 같습니다

<공식 번역어 목록 (없는 것은 알아서 해주세요 ㅎㅎㅎㅎㅎ)>
동아리 목록
공지사항
나의 동아리
동아리 관리 - club management
동아리 등록 신청 - club registration

최근 회의 - recent meeting
전동대회(전체동아리대표자회의) - Club Representatives Council Meeting
확대운영위원회 - Expansive Operative Committee
운영위원회 - Operative Committee
분과회의 - division meeting

소통채널 안내
카카오톡 문의하기
동아리연합회칙 - Clubs Union Constitution

대여 사업 - rental business
홍보물 인쇄 - Promotional Printing Business
활동확인서 발급 - activity report
공용공간 비정기사용 - common space usage

## 스크린샷

![Width=961px~1200px](https://github.com/academic-relations/ar-002-clubs/assets/33417582/a85fa0ef-f83a-4343-9676-648a7e216a7a)
![NavSubMenu](https://github.com/academic-relations/ar-002-clubs/assets/33417582/6c3c9eb9-1add-4460-a5b9-2778de907871)
![NavItem](https://github.com/academic-relations/ar-002-clubs/assets/33417582/319784e5-2ae2-43b6-a133-ebd5bc3e3d11)

**Comment by predict-woo** [comment]
@babycroc  i18n 써야 할까요?

**Comment by babycroc** [comment]
@predict-woo 아직 셋업이 안된걸로 알고 있어서 일단은 안해도 될 것 같은데 (추후에 i18n 사용하게끔 변경하는 게 어렵지는 않죠?? 나 잘 몰라서..) 지호한테 물어보니 오늘 내로 셋업 된다고는 하네요
번역 리스트 준 이유는 i18n 적용보다는 변수 네이밍 때문이어서 상우 편한대로 작업 시작해주시면 돼요~~

**Comment by predict-woo** [comment]
@babycroc 혹시 각 항목 위에 hover했을 때 각 항목에 대한 세부항목만 나오면 될까요 아니면 전체가 나와야 할까요?

**Comment by babycroc** [comment]
@predict-woo 각 항목만! like ara
