### ISSUE TITLE
Block mobile view

### ISSUE THREAD

**Issue by babycroc** [academic-relations/ar-002-clubs#212]
# 제안 내용 \*

모바일 반응형 화면이 거의 없음 (모바일 하려면 모바일용 폰트 크기도 고려해야 해서 상당히 많은 리소스가 듬)
종강종회 때는 모바일 (720px 이하)일 경우 화면에 아직 모바일 지원 안된다는 문구 정도 표시하면 어떨까 함

## 스크린샷

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by wjeongchoi** [comment]
도라가 닫으래요
