### ISSUE TITLE
Impl my page service pages

### ISSUE THREAD

**Issue by babycroc** [academic-relations/ar-002-clubs#214]
# 제안 내용 \*

마이페이지에서 이동 가능한 서비스 신청 내역 페이지 개발 + 마이페이지와 연결
https://github.com/academic-relations/ar-002-clubs/pull/131 머지 + https://github.com/academic-relations/ar-002-clubs/issues/115 개발 후에 진행

## 스크린샷

![image](https://github.com/academic-relations/ar-002-clubs/assets/33417582/73a38ef4-2d61-4d95-8382-c8c7df59ebba)

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by babycroc** [comment]
@wjeongchoi 이거 저희 해커톤 할 때 완료됐었지 않나? 확인 후 관련 PR 연결해주고 다 된거면 close해도 좋을듯~

**Comment by wjeongchoi** [comment]
> @wjeongchoi 이거 저희 해커톤 할 때 완료됐었지 않나? 확인 후 관련 PR 연결해주고 다 된거면 close해도 좋을듯~

아 이거 /manage-club 하위 유사한 페이지들이 완료된거고 /my 하위에 있는 건 안 되어 있음
유사한 코드니까 이번주 중으로 빠르게 완료해둘게용
