### ISSUE TITLE
Typography component refactoring

### ISSUE THREAD

**Issue by babycroc** [academic-relations/ar-002-clubs#314]
# 제안 내용 \*

`Typography` 컴포넌트의 prop 중 type을 통한 custom styling이 되게끔 하는 부분을 제외하고, 항상 font size나 weight 등을 prop으로 받게끔 한다  (https://github.com/academic-relations/ar-002-clubs/blob/dev/packages/web/src/common/components/Typography.tsx)

default font weight는 400(regular), font color는 black(#333333)으로 해주세요

### As-is
```
type TypographyProps =
  | (TypographyPropsWithType & {
      fs?: never;
      lh?: never;
      fw?: never;
      color?: never;
    })
  | (TypographyPropsWithCustomStyles & { type?: never });
```

### To-be
```
type TypographyProps = {
  fs?: never;
  lh?: never;
  fw?: never;
  color?: never;
};
```

## 스크린샷

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by wjeongchoi** [comment]
이거 default font family PRETENDARD도 추가 부탁합니당
