### ISSUE TITLE
packages.json : pnpm 버전이 맞지 않음

### ISSUE THREAD

**Issue by jinhyeonkwon** [academic-relations/ar-002-clubs#316]
# 이슈 내용 \*

`engines`에는 pnpm 버전이 8.0.0으로 되어 있고, `packageManager`에는 8.15.8로 되어 있습니다.
Windows WSL2를 사용하는 제 환경 기준으로, pnpm 버전을 8.0.0으로 하면 패키지 중 일부(약 300~400개)가 제대로 설치되지 않습니다. 8.15.8로 하면 정상 설치됩니다. 이에 `engines`에 명시된 pnpm 버전을 바꾸고자 합니다.

**Comment by jinhyeonkwon** [comment]
packages.json은 수정하지 않고, 설치하는 pnpm 버전만 8.15.8로 하면 해결됩니다

**Comment by babycroc** [comment]
@jinhyeonkwon 

`engines`에 있는 pnpm version은 `8.0.0`이 아니라 `^8.0.0`이에요!! ([참고](https://github.com/academic-relations/ar-002-clubs/blob/dev/package.json#L51-L55)) 

`^`(caret notation)의 의미는 [여기](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#dependencies)에서 볼 수 있구, major version이 8인 latest pnpm version이 `8.15.8`이라서 `packageManager` version이 저렇게 설정되어 있을거에요!

참고하시라구 코멘트 남겨놓아요~

**Comment by jinhyeonkwon** [comment]
앗 제가 이 notation의 의미를 제대로 파악하지 않아 혼란을 겪었군요! 알려주셔서 감사합니다!
