### ISSUE TITLE
Impl modals for club member registration

### ISSUE THREAD

**Issue by babycroc** [academic-relations/ar-002-clubs#452]
# 제안 내용 \*

RegisterMemberConfirm, RegisterMemberCancel

기존에 구현되어 있는 modal 관련 컴포넌트 이용

/clubs/[id]에는 구현이 되어서 /clubs 페이지만 작업해주시면 됩니다!

## 스크린샷

https://www.figma.com/design/gm0BeqvuY5dsA86XyRgEc3/%ED%95%99%EC%88%A0%ED%98%91%EB%A0%A5-02.-%5B%EB%8F%99%EC%97%B0%ED%98%91%EB%A0%A5%EC%82%AC%EC%97%85%5D?node-id=5903-46453&t=PLd7YiCkdxCMBp5c-11

<img width="350" alt="image" src="https://github.com/user-attachments/assets/0d15e6e3-2695-453d-ba2d-a0c19e3aa7a0">

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by callasio** [comment]
https://github.com/academic-relations/ar-002-clubs/blob/0818b41a789fa1d477708ee7c089d645b74e1a3e/packages/web/src/features/clubs/components/ClubCard.tsx#L87-L93

이게 /clubs 페이지 들어가면 보이는 등록 신청 버튼이에요! onClick() 안에 내용 수정해서 테스트 해주시면 됩니당
