### ISSUE TITLE
Some texts follow the font from default sans-serif font configuration of browser

### ISSUE THREAD

**Issue by callasio** [academic-relations/ar-002-clubs#533]
# 이슈 내용 \*

Typography로 감싼 텍스트도 browser의 sans-serif 설정을 다르게 하면 바뀜

하지만 모든 텍스트가 그런 것은 아님

## 스크린샷

![image](https://github.com/user-attachments/assets/70130ba1-4599-4545-85b0-35625785a9b7)

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by babycroc** [comment]
(참고) https://github.com/academic-relations/ar-002-clubs/pull/528#issuecomment-2266504289

**Comment by babycroc** [comment]
(참고) https://sparcs.slack.com/archives/C06SM9MN25C/p1722675328290079

**Comment by wjeongchoi** [comment]
https://github.com/academic-relations/ar-002-clubs/issues/535
