### ISSUE TITLE
main page notice frame mobile

### ISSUE THREAD

**Issue by babycroc** [academic-relations/ar-002-clubs#659]
# 제안 내용 \*

메인 화면 공지사항 list 반응형 (찔끔 차이가 나요)

## 스크린샷

현재 이렇고
<img width="530" alt="image" src="https://github.com/user-attachments/assets/15d7639e-d1a0-4ff1-bb9d-0e4a3826eaaa">

이렇게 되어야해여
https://www.figma.com/design/gm0BeqvuY5dsA86XyRgEc3/%ED%95%99%EC%88%A0%ED%98%91%EB%A0%A5-02.-%5B%EB%8F%99%EC%97%B0%ED%98%91%EB%A0%A5%EC%82%AC%EC%97%85%5D?node-id=7958-92315&t=pjwUu98IaGx3nMN9-11
<img width="354" alt="image" src="https://github.com/user-attachments/assets/3bcb0d4b-39be-496e-8a93-4e38b796b0d8">

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by malloc3141** [comment]
날짜가 YYYY.MM.DD. --> YY.MM.DD. 형식으로 보여야 한다는 뜻인가요??

**Comment by babycroc** [comment]
> 날짜가 YYYY.MM.DD. --> YY.MM.DD. 형식으로 보여야 한다는 뜻인가요??

그것도 그렇고 글자 크기나 padding gap 같은 게 조금씩 달라용!
