### ISSUE TITLE
fix 60px gap to 40px for pages of width 721px to 960px

### ISSUE THREAD

**Issue by babycroc** [academic-relations/ar-002-clubs#663]
# 제안 내용 \*

gap이 60px인 경우가 많은데 721px ~ 960px 일 때 40px로 바꿔주세요

메인 페이지
공지사항
동아리 목록
동아리 상세
마이페이지
등등..

일단은 이 정도만?

## 스크린샷

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by jinhyeonkwon** [comment]
동아리 상세 -> https://github.com/academic-relations/ar-002-clubs/pull/683
