### ISSUE TITLE
fix bug for search on clubs page

### ISSUE THREAD

**Issue by babycroc** [academic-relations/ar-002-clubs#664]
# 제안 내용 \*

동아리 목록 페이지 검색 고치기
- ~검색어 없을 경우 전체 리스트 보이게 해주세요~ 는 되어 있는 거 확인했구
- **한 글자 입력할 때마다 인풋 focus가 풀리는 것 같은데** 저만 그런가용? 그래서 검색 테스트 불가

## 스크린샷

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by wjeongchoi** [comment]
이거 테스트할 때는 괜찮았는데 지금 dev에서 안되는군,,

**Comment by ChaeyeonAhn** [comment]
으앗 그렇군요 오늘 저녁에 고쳐보겠습니다..!!!
