### ISSUE TITLE
My Club Page -  Club Type Error

### ISSUE THREAD

**Issue by Davidace136** [academic-relations/ar-002-clubs#68]
# 이슈 내용 \*

다른 페이지들은 정상적으로 작동하나, /my 링크를 들어가면 My Club Page가 컴파일 되면서 드러나지 않았던 에러가 사이트 자체의 compile을 막아버린다. 해결 방법은 에러의 원인을 해결하는 것이다.

사건의 개요 : 영미님이 먼저 My Club Page를 완료하고 merge 한 이후, 백엔드 API와 관련하여 mock data의 type 및 형식을 완전히 바꾸는 merge가 누군가에 의해 일어났다. 따라서 해당 merge 이후부터 My Club Page는 당연히 비활성화 되었을 것이지만, 누구도 dev에서 My Club Page를 열어볼 생각을 하지 않아 지금까지 에러가 묻혀 있던 것이다.

백엔드 관련 merge 전에는 원래 ClubInfo나 RawClubsData와 같은 것들을 이용하여 mock data를 받아왔었으나, 지금은 해당 mock data가 사라졌다. 
### **따라서 새로운 mock data를 활용해서 My Clubs Page에 data를 먹여주도록 수정해야 함!**

Clubs List Page의 merge 과정에서 @Davidace136 이 아래 위치에 mock data를 마련해두었으니 사용 바람! (Clubs List Page가 사용 중인 mock data이다)
```
/packages/web/src/features/clubs/services/_mock/mockupClubData.ts
``` 

해당 mock data 사용 예시는 아래와 같다
```typescript
import AsyncBoundary from "@sparcs-clubs/web/common/components/AsyncBoundary";
import { useGetClubsList } from "@sparcs-clubs/web/features/clubs/services/useGetClubsList";
...
const TempFrame: React.FC = () => {
  const { data, isLoading, isError } = useGetClubsList(); //얘가 mock data 알아서 가져와줌
  return (
    <AsyncBoundary isLoading={isLoading} isError={isError}> //mock data 로딩 전까지 빙글빙글 도는 placeholder
      <div>
        { data } // data 원하는대로 사용
      </div>
    </AsyncBoundary>

  );
}
```

실 사용 예시를 참고하고 싶다면 아래 위치에서 확인할 것!
```
packages/web/src/features/clubs/frames/ClubsPageMainFrame.tsx
```

## 스크린샷

<img width="1440" alt="스크린샷 2024-04-04 오후 11 59 17" src="https://github.com/academic-relations/ar-002-clubs/assets/43981717/c5a2e5b0-58a9-4613-8c1b-e9f79af26df7">

# 관련 Task \*

- [ ] Mock Data 수신 방식 변경
- [ ] My Clubs Page 정상 작동 및 에러 해결 확인

**Comment by Engineer-JJHaMa** [comment]
인터페이스가 디자인과 프론트가 나오는게 빠르던 시점에 구현이 되어서
- 자체적으로 타입과 mock을 세팅하고 사용
- service 구현을 스킵하고 구성
두가지가 필연적으로 일어난 것 같아요! 앞으로는 인터페이스가 빠릿빠릿하게 나와서 인터페이스 업싱 구현하는 일이 없도록 하겠습니다 🙇

**Comment by Davidace136** [comment]
앗 아닙니다! 제가 좀 더 빠르게 머지했어야 했는데 ㅠㅠ 감사드립니다!
