### ISSUE TITLE
Test and improve member-registration list (REG-006)

### ISSUE THREAD

**Issue by Engineer-JJHaMa** [academic-relations/ar-002-clubs#685]
# 제안 내용 \*

등록 기능 중
회원 등록에서 자신이 신청한 동아리 목록을 돌려주는
REG-006의 테스트와 개선이 필요합니다.

프론트 요청에 따라 동아리 회원 등록 기간 외의 기간에는
204와 함께 빈 배열을 리턴합니다.
테스트 중 다른 이슈에 의해 REG-005의 로직에 변경이 발생할 수 있습니다.

## 스크린샷

<img width="1577" alt="스크린샷 2024-08-21 오후 12 39 27" src="https://github.com/user-attachments/assets/b13f194d-5b6a-4ff0-84fb-6cdd1a6791b4">

# 관련 Task \*

- [x] REG-006 테스트하기

**Comment by oRE-o** [comment]
DB에 Enum들이 비어있어 채우고 나서 테스트 진행했습니다.

로그인 과정 진행 후 REG-005를 통해 clubid를 전달해 신청이 가능합니다.
REG-006를 통해 학생의 신청 상황을 확인 가능합니다.

코드 수정 사항이 없어서 branch 만들지 않고 Issue Close 합니다.
