### ISSUE TITLE
mobile /credits page minor design fix

### ISSUE THREAD

**Issue by babycroc** [academic-relations/ar-002-clubs#766]
# 이슈 내용 \*

붉은 선에 align
표시한 gap들도 /clubs 페이지에 있는 mobile 기준 gap이랑 같게 해주세용 

## 스크린샷

![image](https://github.com/user-attachments/assets/5bae0fbd-dde7-4bda-acec-621ada2f9ba7)

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by jinhyeonkwon** [comment]
이거 720px 이하 구간을 확인해 보았더니 Figma에 맞는 gap, padding과 일치하는 것 같아요! 다른 (수많은) PR 사이에서 수정된 듯?

**Comment by babycroc** [comment]
@jinhyeonkwon 놀랍게도... 아니야!
내 요구사항은 요 선에 맞추는 것 + 저 박스 높이 20px로 줄이는 것이었다 ㅎㅎ..
모바일일 때 pagetitle 달라지면서 간혹 저 좌측 패딩이 넓어보이는 경우가 종종 잇어성

<img width="498" alt="Screenshot 2024-08-23 at 3 11 05 AM" src="https://github.com/user-attachments/assets/cbb8780b-4d08-4257-9132-f1f555056a1e">
