### ISSUE TITLE
/manage-club page bug when no club to manage

### ISSUE THREAD

**Issue by babycroc** [academic-relations/ar-002-clubs#767]
# 이슈 내용 \*

대표자 또는 대의원인 동아리가 없을 경우 뜨는 화면이에요
뭔가 새로고침하면 뒤에 힐끔힐끔 보이는 게 거슬리는데 완전히 가려졌으면 좋겟궁
추가로 "나의 동아리 바로가기"도 안되는 것 같아서? 같이 제보해여

## 스크린샷

https://github.com/user-attachments/assets/ff9f6af6-644d-4cc9-83ac-b73d6d6239dd

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by wjeongchoi** [comment]
나의 동아리 바로가기는 연결함
