### ISSUE TITLE
connect backend for my page info frame

### ISSUE THREAD

**Issue by wjeongchoi** [academic-relations/ar-002-clubs#806]
# 제안 내용 \*
저장되어 있는 전화번호 불러오기 수정 (연결은 되어있으나, 반영이 잘 되지 않음) - useGetUserProfile 사용
전화번호 수정해서 저장하기 (현재 api 없음, 업데이트 예정)

## 스크린샷
<img width="716" alt="스크린샷 2024-08-23 오전 4 18 40" src="https://github.com/user-attachments/assets/9eca19a0-8eb3-4eb4-846e-b95c3f1bba5e">

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by malloc3141** [comment]
![image](https://github.com/user-attachments/assets/6b4fd3e6-13ec-48b6-9362-1ccca348383b)
api 문서 보니까 USR-002에 유저의 현재 전화번호를 가져오는 api가 따로 있는데 이 친구로 구현해야 하나요 아니면 이슈에 언급된대로 useGetUserProfile 구현되어있는 거 그대로 가져다 쓰면 될까요?

+ 근데 확인해보니 어차피 전화번호 수정하는 api도 미구현이었어요 ㅎㅎ;
